[build]
  command = "npm install"
  publish = "public"

[dev]
  command = "npm start"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"

[build.environment]
  NODE_VERSION = "18"
